[package]
name = "ends_bb_mod_tools"
version = "0.0.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5.11"
walkdir = "2"
dirs-next = "2.0.0"
open = "1"